// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTXYB3UXxUd1uAaH8MzY4NH_0rdrT2ouM',
    appId: '1:519576392172:web:ff8dfff9dbab855521b0c9',
    messagingSenderId: '519576392172',
    projectId: 'clone-965d6',
    authDomain: 'clone-965d6.firebaseapp.com',
    storageBucket: 'clone-965d6.firebasestorage.app',
    measurementId: 'G-K3BWHT98D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQh0yNBWvBXwwMBbrYxGQEv4cr2Ahgb9s',
    appId: '1:519576392172:android:fd6865f312028ec321b0c9',
    messagingSenderId: '519576392172',
    projectId: 'clone-965d6',
    storageBucket: 'clone-965d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4p5vrQC8FFgZkRUO-hCQFHm41TX6jk0o',
    appId: '1:519576392172:ios:e506cf78072f339e21b0c9',
    messagingSenderId: '519576392172',
    projectId: 'clone-965d6',
    storageBucket: 'clone-965d6.firebasestorage.app',
    iosClientId: '519576392172-v5c7mgin7goas05rvnrvh9l4g1rboahl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmailClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4p5vrQC8FFgZkRUO-hCQFHm41TX6jk0o',
    appId: '1:519576392172:ios:e506cf78072f339e21b0c9',
    messagingSenderId: '519576392172',
    projectId: 'clone-965d6',
    storageBucket: 'clone-965d6.firebasestorage.app',
    iosClientId: '519576392172-v5c7mgin7goas05rvnrvh9l4g1rboahl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmailClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTXYB3UXxUd1uAaH8MzY4NH_0rdrT2ouM',
    appId: '1:519576392172:web:296d852939d71fc921b0c9',
    messagingSenderId: '519576392172',
    projectId: 'clone-965d6',
    authDomain: 'clone-965d6.firebaseapp.com',
    storageBucket: 'clone-965d6.firebasestorage.app',
    measurementId: 'G-F6ZZYT9GBP',
  );
}
